# Generated by Django 4.2.1 on 2023-05-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
